server:
  port: 10033
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/devops?serverTimezone=GMT
    username: root
    password: 666888
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    mode: HTML
cas:
  client-name: client0
  server:
    url: http://www.cas.com
  project:
    url: http://www.ssoclient2.com:10033

#    suffix: .html
#mybatis:
#  config-location: